version: "3.7"
services:
  app:
    build:
      args:
        user: '1012'
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gallery
    container_name: pendaftaran-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - gallery

  db:
    image: mysql:8.0
    container_name: pendaftaran-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: gallery
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - gallery

  nginx:
    image: nginx:alpine
    container_name: pendaftaran-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - gallery

networks:
  gallery:
    driver: bridge